//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KhiRobot
{
    [Serializable]
    public class KhiRobotCmdResponse : Message
    {
        public const string k_RosMessageName = "khi_robot_msgs/KhiRobotCmd";
        public override string RosMessageName => k_RosMessageName;

        public int driver_ret;
        public int as_ret;
        public string cmd_ret;

        public KhiRobotCmdResponse()
        {
            this.driver_ret = 0;
            this.as_ret = 0;
            this.cmd_ret = "";
        }

        public KhiRobotCmdResponse(int driver_ret, int as_ret, string cmd_ret)
        {
            this.driver_ret = driver_ret;
            this.as_ret = as_ret;
            this.cmd_ret = cmd_ret;
        }

        public static KhiRobotCmdResponse Deserialize(MessageDeserializer deserializer) => new KhiRobotCmdResponse(deserializer);

        private KhiRobotCmdResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.driver_ret);
            deserializer.Read(out this.as_ret);
            deserializer.Read(out this.cmd_ret);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.driver_ret);
            serializer.Write(this.as_ret);
            serializer.Write(this.cmd_ret);
        }

        public override string ToString()
        {
            return "KhiRobotCmdResponse: " +
            "\ndriver_ret: " + driver_ret.ToString() +
            "\nas_ret: " + as_ret.ToString() +
            "\ncmd_ret: " + cmd_ret.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
