//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KhiRobot
{
    [Serializable]
    public class KhiRobotCmdRequest : Message
    {
        public const string k_RosMessageName = "khi_robot_msgs/KhiRobotCmd";
        public override string RosMessageName => k_RosMessageName;

        public string type;
        public string cmd;

        public KhiRobotCmdRequest()
        {
            this.type = "";
            this.cmd = "";
        }

        public KhiRobotCmdRequest(string type, string cmd)
        {
            this.type = type;
            this.cmd = cmd;
        }

        public static KhiRobotCmdRequest Deserialize(MessageDeserializer deserializer) => new KhiRobotCmdRequest(deserializer);

        private KhiRobotCmdRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
            deserializer.Read(out this.cmd);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
            serializer.Write(this.cmd);
        }

        public override string ToString()
        {
            return "KhiRobotCmdRequest: " +
            "\ntype: " + type.ToString() +
            "\ncmd: " + cmd.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
