controller_list:
  - name: upper_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - upper_gripper_finger_left_joint
      - upper_gripper_finger_right_joint
  - name: lower_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - lower_gripper_finger_left_joint
      - lower_gripper_finger_right_joint
  - name: upper_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - duaroupper_joint1
      - duaroupper_joint2
      - duaroupper_joint3
      - duaroupper_joint4
  - name: lower_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - duarolower_joint1
      - duarolower_joint2
      - duarolower_joint3
      - duarolower_joint4
  - name: botharms_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - duarolower_joint1
      - duarolower_joint2
      - duarolower_joint3
      - duarolower_joint4
      - duaroupper_joint1
      - duaroupper_joint2
      - duaroupper_joint3
      - duaroupper_joint4