behaviors:
  DuaroAgentComplex:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.0004
      beta: 0.003
      epsilon: 0.20
      lambd: 0.91
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.92
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 3000000
    time_horizon: 64
    summary_freq: 1000