//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FileServer
{
    [Serializable]
    public class GetBinaryFileResponse : Message
    {
        public const string k_RosMessageName = "file_server/GetBinaryFile";
        public override string RosMessageName => k_RosMessageName;

        public byte[] value;

        public GetBinaryFileResponse()
        {
            this.value = new byte[0];
        }

        public GetBinaryFileResponse(byte[] value)
        {
            this.value = value;
        }

        public static GetBinaryFileResponse Deserialize(MessageDeserializer deserializer) => new GetBinaryFileResponse(deserializer);

        private GetBinaryFileResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.value);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "GetBinaryFileResponse: " +
            "\nvalue: " + System.String.Join(", ", value.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
