//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FileServer
{
    [Serializable]
    public class SaveBinaryFileResponse : Message
    {
        public const string k_RosMessageName = "file_server/SaveBinaryFile";
        public override string RosMessageName => k_RosMessageName;

        public string name;

        public SaveBinaryFileResponse()
        {
            this.name = "";
        }

        public SaveBinaryFileResponse(string name)
        {
            this.name = name;
        }

        public static SaveBinaryFileResponse Deserialize(MessageDeserializer deserializer) => new SaveBinaryFileResponse(deserializer);

        private SaveBinaryFileResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "SaveBinaryFileResponse: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
