//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FileServer
{
    [Serializable]
    public class SaveBinaryFileRequest : Message
    {
        public const string k_RosMessageName = "file_server/SaveBinaryFile";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public byte[] value;

        public SaveBinaryFileRequest()
        {
            this.name = "";
            this.value = new byte[0];
        }

        public SaveBinaryFileRequest(string name, byte[] value)
        {
            this.name = name;
            this.value = value;
        }

        public static SaveBinaryFileRequest Deserialize(MessageDeserializer deserializer) => new SaveBinaryFileRequest(deserializer);

        private SaveBinaryFileRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.value, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.WriteLength(this.value);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "SaveBinaryFileRequest: " +
            "\nname: " + name.ToString() +
            "\nvalue: " + System.String.Join(", ", value.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
