lower_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - lower_joint1
    - lower_joint2
    - lower_joint3
    - lower_joint4
  gains:
    lower_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lower_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lower_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lower_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
upper_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - upper_joint1
    - upper_joint2
    - upper_joint3
    - upper_joint4
  gains:
    upper_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
upper_arm_tool_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - upper_joint4
  gains:
    upper_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
lower_arm_tool_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - lower_joint4
  gains:
    lower_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
botharms_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - lower_joint1
    - lower_joint2
    - lower_joint3
    - lower_joint4
    - upper_joint1
    - upper_joint2
    - upper_joint3
    - upper_joint4
  gains:
    lower_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lower_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lower_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lower_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1